#!/bin/sh /etc/rc.common

#https://openwrt.org/docs/techref/initscripts

#https://stackoverflow.com/questions/33340659/how-to-auto-start-an-application-in-openwrt
#$ chmod +x /etc/init.d/
#$ /etc/init.d/`basename $0` enable
#$ ls -lh /etc/rc.d | grep `basename $0`
#$ /etc/init.d/`basename $0` enabled && echo on

# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=50
STOP=90

pkg_realdirname=/repo/github.com/hongyi-zhao/homeshare.git/Public/repo/github.com/fatedier

frps=$pkg_realdirname/frps
frpc=$pkg_realdirname/frpc

frps_ini=$pkg_realdirname/frps-pve-openwrt.ini
frpc_ini=$pkg_realdirname/frpc-pve-openwrt.ini

start() {        
        nohup $frps -c $frps_ini >/dev/null 2>&1 &
        pid=$!
        #https://unix.stackexchange.com/questions/68693/how-to-know-if-a-background-job-is-finished 
        sleep 2
        if kill -0 $pid; then
          $frpc -c $frpc_ini >/dev/null 2>&1 &
        fi 
}                 
 
stop() {          
        pkill -f frpc
        pkill -f frps
}
