#!/bin/sh /etc/rc.common

#https://openwrt.org/docs/techref/initscripts

#https://stackoverflow.com/questions/33340659/how-to-auto-start-an-application-in-openwrt
#$ chmod +x /etc/init.d/
#$ /etc/init.d/`basename $0` enable
#$ ls -lh /etc/rc.d | grep `basename $0`
#$ /etc/init.d/`basename $0` enabled && echo on

# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=50
STOP=90

pkg_realdirname=/repo/github.com/hongyi-zhao/homeshare.git/Public/repo/github.com/fatedier
frps_ini=$pkg_realdirname/frps.ini
start() {        
        nohup frps -c $frps_ini >/dev/null 2>&1 &
}                 
 
stop() {          
        pkill -f frps
}
